server:
  port: 8000
  servlet:
    context-path: /user-service

logging:
  level:
    org:
      springframework:
        cloud: trace

spring:
  application:
    name: user-service

  main:
    banner-mode: off

  config:
    import: "optional:kubernetes:"
  cloud:
    kubernetes:
      reload:
        enabled: true
        strategy: refresh
      config:
        fail-fast: true
      secrets:
        fail-fast: true

  datasource:
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate.globally_quoted_identifiers: true
